os: linux
dist: bionic

language: perl

addons:
  apt:
    packages:
      - ttf-dejavu

perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"

install:
    - dzil authordeps --missing | cpanm -n || { cat ~/.cpanm/build.log ; false ; }
    - dzil listdeps   --missing | cpanm -n || { cat ~/.cpanm/build.log ; false ; }

script:
    - dzil test --author --release
